apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    env: uat-env
    app: eb-ms-app
  namespace: default
spec:
  containers:
    - name: eb-ms-nginx-instance
      image: nginx
      ports:
        - name: nginx
          containerPort: 80